logging.level: info 

filebeat.prospectors:

- type: log
  paths:
    - /var/kipp/logs/**/*.log
  include_lines: ['.Spider opened', '.ERROR', '.Dropped: Item is not valid', '.DEBUG: Scraped from', '.WARNING: Item at url']
  #exclude_lines: ['.Spider closed', '.statscollectors.']
  exclude_files: ['.live_extractor', '.scrapyd', '.polipo', '.kipp_', 'test']
  enabled: true 
  fields_under_root: true
  fields:
    spider_state: "running"
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}[[:space:]][0-9]{2}:[0-9]{2}:[0-9]{2}[[:space:]]'
    negate: true
    match: after

- type: log
  paths:
    - /var/kipp/logs/**/*.log
  include_lines: ['.statscollectors']
  #exclude_lines: ['.errors detected', '.ERROR', '.Spider closed', '.Dropped: Item is not valid', '.DEBUG: Scraped from', '.WARNING: Item at url']
  exclude_files: ['.live_extractor', '.scrapyd', '.polipo', '.kipp_', 'test']
  enabled: true
  fields_under_root: true
  fields:
    spider_state: "finished"
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}[[:space:]][0-9]{2}:[0-9]{2}:[0-9]{2}[[:space:]]'
    negate: true
    match: after

- type: log
  paths:
    - /var/kipp/logs/**/*.log
  include_lines: ['.Spider closed']
  #exclude_lines: ['.Spider opened', '.ERROR', '.Dropped: Item is not valid', '.DEBUG: Scraped from', '.WARNING: Item at url']
  exclude_files: ['.live_extractor', '.scrapyd', '.polipo', '.kipp_', 'test']
  enabled: true
  fields_under_root: true
  fields:
    spider_state: "closed"
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}[[:space:]][0-9]{2}:[0-9]{2}:[0-9]{2}[[:space:]]'
    negate: true
    match: after


output.logstash:
  hosts: ["192.168.1.94:5045"]

