logging.level: info
filebeat.prospectors:
- type: log
  paths:
    - /var/kipp/logs/**/*.log
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}[[:space:]][0-9]{2}:[0-9]{2}:[0-9]{2}[[:space:]]'
    negate: true
    match: after

output.logstash:
  hosts: ["logstash:5044"]
