filebeat.prospectors:
- type: log
  paths:
    - /var/kipp/logs/**/*.log
  include_lines: ['.Dumping Scrapy stats', '.INFO', '.ERROR', '.Dropped: Item is not valid', '.DEBUG: Scraped from', '.WARNING: Item at url']
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}[[:space:]][0-9]{2}:[0-9]{2}:[0-9]{2}[[:space:]]'
    negate: true
    match: after


output.logstash:
  hosts: ["logstash:5044"]
