filebeat.prospectors:
- type: Finished
  paths:
    - /logs/logs/finished/**/*.log
  multiline:
    pattern: '^%{TIMESTAMP_ISO8601} '
    match: after

- type: Running
  paths:
    - /logs/logs/running/**/*.log
  multiline:
    pattern: '^%{TIMESTAMP_ISO8601} '
    match: after

output.logstash:
  hosts: ["localhost:5043"]
